# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from swagger_server.models.base_model_ import Model
from swagger_server import util


class MachineLearningJobPysparkJob(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, main_python_file_uri: str=None, jar_file_uris: str=None):  # noqa: E501
        """MachineLearningJobPysparkJob - a model defined in Swagger

        :param main_python_file_uri: The main_python_file_uri of this MachineLearningJobPysparkJob.  # noqa: E501
        :type main_python_file_uri: str
        :param jar_file_uris: The jar_file_uris of this MachineLearningJobPysparkJob.  # noqa: E501
        :type jar_file_uris: str
        """
        self.swagger_types = {
            'main_python_file_uri': str,
            'jar_file_uris': str
        }

        self.attribute_map = {
            'main_python_file_uri': 'mainPythonFileUri',
            'jar_file_uris': 'jarFileUris'
        }

        self._main_python_file_uri = main_python_file_uri
        self._jar_file_uris = jar_file_uris

    @classmethod
    def from_dict(cls, dikt) -> 'MachineLearningJobPysparkJob':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineLearning_job_pysparkJob of this MachineLearningJobPysparkJob.  # noqa: E501
        :rtype: MachineLearningJobPysparkJob
        """
        return util.deserialize_model(dikt, cls)

    @property
    def main_python_file_uri(self) -> str:
        """Gets the main_python_file_uri of this MachineLearningJobPysparkJob.


        :return: The main_python_file_uri of this MachineLearningJobPysparkJob.
        :rtype: str
        """
        return self._main_python_file_uri

    @main_python_file_uri.setter
    def main_python_file_uri(self, main_python_file_uri: str):
        """Sets the main_python_file_uri of this MachineLearningJobPysparkJob.


        :param main_python_file_uri: The main_python_file_uri of this MachineLearningJobPysparkJob.
        :type main_python_file_uri: str
        """

        self._main_python_file_uri = main_python_file_uri

    @property
    def jar_file_uris(self) -> str:
        """Gets the jar_file_uris of this MachineLearningJobPysparkJob.


        :return: The jar_file_uris of this MachineLearningJobPysparkJob.
        :rtype: str
        """
        return self._jar_file_uris

    @jar_file_uris.setter
    def jar_file_uris(self, jar_file_uris: str):
        """Sets the jar_file_uris of this MachineLearningJobPysparkJob.


        :param jar_file_uris: The jar_file_uris of this MachineLearningJobPysparkJob.
        :type jar_file_uris: str
        """

        self._jar_file_uris = jar_file_uris
