# coding: utf-8

from __future__ import absolute_import
from datetime import date, datetime  # noqa: F401

from typing import List, Dict  # noqa: F401

from app.models.base_model_ import Model
from app import util


class MachineLearningJobReference(Model):
    """NOTE: This class is auto generated by the swagger code generator program.

    Do not edit the class manually.
    """

    def __init__(self, job_id: str=None):  # noqa: E501
        """MachineLearningJobReference - a model defined in Swagger

        :param job_id: The job_id of this MachineLearningJobReference.  # noqa: E501
        :type job_id: str
        """
        self.swagger_types = {
            'job_id': str
        }

        self.attribute_map = {
            'job_id': 'jobId'
        }

        self._job_id = job_id

    @classmethod
    def from_dict(cls, dikt) -> 'MachineLearningJobReference':
        """Returns the dict as a model

        :param dikt: A dict.
        :type: dict
        :return: The MachineLearning_job_reference of this MachineLearningJobReference.  # noqa: E501
        :rtype: MachineLearningJobReference
        """
        return util.deserialize_model(dikt, cls)

    @property
    def job_id(self) -> str:
        """Gets the job_id of this MachineLearningJobReference.


        :return: The job_id of this MachineLearningJobReference.
        :rtype: str
        """
        return self._job_id

    @job_id.setter
    def job_id(self, job_id: str):
        """Sets the job_id of this MachineLearningJobReference.


        :param job_id: The job_id of this MachineLearningJobReference.
        :type job_id: str
        """

        self._job_id = job_id
